# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoCatr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='Rusers',
        ),
    ]
