# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoCatr', '0002_auto_20170423_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pumps_stations',
        ),
        migrations.AddField(
            model_name='rusers',
            name='pump_locations',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rusers',
            name='pump_name',
            field=models.CharField(default=12, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rusers',
            name='pump_status',
            field=models.BooleanField(default=False),
        ),
    ]
