# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoCatr', '0003_auto_20170502_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rusers',
            name='pump_locations',
        ),
    ]
